#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : python-keystoneclient
Version  : 3.19.0
Release  : 60
URL      : http://tarballs.openstack.org/python-keystoneclient/python-keystoneclient-3.19.0.tar.gz
Source0  : http://tarballs.openstack.org/python-keystoneclient/python-keystoneclient-3.19.0.tar.gz
Source99 : http://tarballs.openstack.org/python-keystoneclient/python-keystoneclient-3.19.0.tar.gz.asc
Summary  : Client Library for OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: python-keystoneclient-license = %{version}-%{release}
Requires: python-keystoneclient-python = %{version}-%{release}
Requires: python-keystoneclient-python3 = %{version}-%{release}
Requires: debtcollector
Requires: keystoneauth1
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : pbr
Patch1: cve-2015-7546.nopatch

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/python-keystoneclient.svg
:target: https://governance.openstack.org/tc/reference/tags/index.html

%package license
Summary: license components for the python-keystoneclient package.
Group: Default

%description license
license components for the python-keystoneclient package.


%package python
Summary: python components for the python-keystoneclient package.
Group: Default
Requires: python-keystoneclient-python3 = %{version}-%{release}

%description python
python components for the python-keystoneclient package.


%package python3
Summary: python3 components for the python-keystoneclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-keystoneclient package.


%prep
%setup -q -n python-keystoneclient-3.19.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555948295
export CFLAGS="$CFLAGS -fcf-protection=full -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fcf-protection=full -fstack-protector-strong "
export FFLAGS="$CFLAGS -fcf-protection=full -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fcf-protection=full -fstack-protector-strong "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-keystoneclient
cp LICENSE %{buildroot}/usr/share/package-licenses/python-keystoneclient/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-keystoneclient/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
