#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-keystoneclient
Version  : 2.3.1
Release  : 34
URL      : http://tarballs.openstack.org/python-keystoneclient/python-keystoneclient-2.3.1.tar.gz
Source0  : http://tarballs.openstack.org/python-keystoneclient/python-keystoneclient-2.3.1.tar.gz
Summary  : Client Library for OpenStack Identity
Group    : Development/Tools
License  : Apache-2.0
Requires: python-keystoneclient-bin
Requires: python-keystoneclient-python
BuildRequires : GitPython-python
BuildRequires : Sphinx-python
BuildRequires : bandit-python
BuildRequires : coverage-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : flake8-docstrings-python
BuildRequires : hacking
BuildRequires : keyring-python
BuildRequires : keystoneauth1-python
BuildRequires : lxml-python
BuildRequires : msgpack-python-python
BuildRequires : oauthlib-python
BuildRequires : oslo.config
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : positional-python
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : reno-python
BuildRequires : requests-mock-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : stevedore
BuildRequires : tempest-lib-python
BuildRequires : testrepository-python
BuildRequires : testresources
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv
Patch1: cve-2015-7546.nopatch
Patch2: 0001-don-t-ask-for-hard-flake8-docstrings-0.2.1.post1-ver.patch

%description
Python bindings to the OpenStack Identity API (Keystone)
========================================================

%package bin
Summary: bin components for the python-keystoneclient package.
Group: Binaries

%description bin
bin components for the python-keystoneclient package.


%package python
Summary: python components for the python-keystoneclient package.
Group: Default
Requires: keystoneauth1-python
Requires: oslo.config
Requires: oslo.serialization-python
Requires: oslo.utils-python
Requires: positional-python
Requires: prettytable
Requires: requests-python
Requires: stevedore

%description python
python components for the python-keystoneclient package.


%prep
%setup -q -n python-keystoneclient-2.3.1
%patch2 -p1

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/keystone

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
